{{ config(materialized='table') }}

WITH NEW AS (
select 
E.EMPLOYEEID, 
E.EMPLOYEENAME,
E.JOBTITLE,
E.EMPLOYEEGENDER,
E.SUPERVISOR, 
E.ANNUALSALARY,
E.EXTENSION,
E.HIRE_DATE, 
E.SALES_TARGET,
O.salesoffice,O.office
FROM PC_FIVETRAN_DB.DBO_DBO.offices AS O
RIGHT JOIN PC_FIVETRAN_DB.DBO_DBO.EMPLOYEES AS E
ON O.office = E.office
WHERE O._fivetran_deleted = 'false' 
ORDER BY E.EMPLOYEEID
)

SELECT * FROM NEW
