with CTE as 

( 
    SELECT 
    CATEGORYID,
    DEPARTMENT,
    DESCRIPTION AS DESCRIPTIONS,
    CATEGORYNAME ,
    _FIVETRAN_SYNCED
    FROM PC_FIVETRAN_DB.SQL_SERVER_DBO.CATEGORY
    where _FIVETRAN_DELETED= 'FALSE' 
)

SELECT * FROM CTE


